{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "luxe-jewelry-app.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "luxe-jewelry-app.auth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.auth.service.type }}
  ports:
  - port: {{ .Values.auth.service.port }}
    targetPort: {{ .Values.auth.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "luxe-jewelry-app.auth.selectorLabels" . | nindent 4 }}
{{- end }}
