{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "luxe-jewelry-app.fullname" . }}-auth-external
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "luxe-jewelry-app.auth.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}
  target:
    name: auth-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        jwt-secret: "{{ `{{ .jwt_secret }}` }}"
  data:
    - secretKey: jwt_secret
      remoteRef:
        key: {{ .Values.externalSecrets.auth.secretArn }}
        property: jwt_secret
{{- end }}
