{{- if and .Values.externalSecrets.enabled (eq .Values.externalSecrets.secretStoreKind "SecretStore") }}
# This SecretStore is only created when using namespace-scoped SecretStore
# If using ClusterSecretStore, this resource is not needed
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "luxe-jewelry-app.fullname" . }}-aws-secretstore
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "luxe-jewelry-app.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "luxe-jewelry-app.serviceAccountName" . }}
{{- end }}
